# This is a basic workflow to help you get started with Actions

name: Getting Started

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 1. What is in this directory
          ls -a
          echo
          echo 2. Is Java installed?
          java -version
          echo
          echo 3. Is git installed?
          git --version
          echo 4. What about build tools?
          mvn --version
          gradle --version
          ant -version
          echo 5. What is the workspace location?
          echo $RUNNER_WORKSPACE
          echo 6. Who is running this script?
          whoami
          echo 7. How is the disk laid out?
          df
          echo 8. What environment variables are available?
          env
          
